server:
  port: 8080 # ??????????????? 8080?????????

spring:
  datasource:
    # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??????? (????? taskflow_db ????????????)
    url: jdbc:mysql://localhost:3306/taskflow_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    # ?? MySQL ??? (??? root)
    username: root
    # ?? ?? MySQL ?? (?????????????????)
    password: 230011
# MyBatis-Plus ????
mybatis-plus:
  configuration:
    # ?????????????board_id???? Java ??????boardId?
    map-underscore-to-camel-case: true
    # (??) ?? SQL ??????????????????????? SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl